name: "Which branch"
    
on:
    pull_request:
    workflow_dispatch:

jobs:
    job-main:
        runs-on: ubuntu-latest
        steps:
            - name: "hello from special job in main"
              run: | 
                echo "hello world"
    hallo: 
        runs-on: ubuntu-latest
        steps:
            - name: "hello reunited"
              run: | 
                echo "hello world"
     
            - name: "special step in branch"
              run: | 
                echo "hello world"
