name: "Which branch"
    
on:
    pull_request:
    workflow_dispatch:

jobs:
    hallo: 
        runs-on: ubuntu-latest
        steps:
            - name: "hello from main"
              run: | 
                echo "hello world"
