name: "Show PRs/Mine"
    
on:
    workflow_run:
        workflows: [Which branch]
        types: [completed]
    push:
    workflow_dispatch:
jobs:
    list-pull-requests:
        runs-on: ubuntu-latest
        steps:
    
            -   name: bkleinen list pr
                id: pulls
                uses: bkleinen/list-pull-requests@v0.3
                with:
                    token: ${{secrets.GITHUB_TOKEN}}
                    #state: 'open'
                    labels: '["PR-DEPLOY"]'
                    skip_hour: '24'

            -   name: output
                run: |
                    echo '${{ steps.pulls.outputs.pulls }}'
                    echo '${{ steps.pulls.outputs.claim }}'
                    echo '${{ steps.pulls.outputs.filtered }}'

