name: "Another after-PR"
    
on:
    workflow_run:
        workflows: [Which branch]
        types: [completed]

    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: "this could deploy on the main branch"
              run: | 
                echo "hello world"
    echo-event: 
        runs-on: ubuntu-latest
        steps:
            -   name: Branch
                env: 
                    GITHUB_REF: ${{ github.ref_name }}
                run: |
                  echo $GITHUB_REF
            - name: Save PR number
              env:
                PR_NUMBER: ${{ github.event.number }}
              run: |
                echo $PR_NUMBER 
        
            - name: "hello from main"
              env:
                PR_CONTEXT: ${{ toJson(github.event.workflow_run) }} 
              run: | 
                echo $PR_CONTEXT
    on-success:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
          - run: echo 'The triggering workflow passed'
    on-failure:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        steps:
          - run: echo 'The triggering workflow failed'
