name: "My Action"
    
on:
    push:

    workflow_dispatch:
jobs:
    my-action:
        runs-on: ubuntu-latest
        steps:
    
            -   name: my action
                id: myaction
                uses: bkleinen/hello-world-javascript-action@v1.3

            -   name: output
                run: |
                    echo  "${{ steps.myaction.outputs.time }}"

       
