name: "My Action"
    
on:
    push:

    workflow_dispatch:
jobs:
    hello-world:
        runs-on: ubuntu-latest
        steps:
    
            -   name: my action
                id: list
                uses: bkleinen/hello-world-javascript-action@v1.3
       
